### ISSUE TITLE
Priority queue

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/p-queue#1]
Add argument on `.add` method to provide priority to task. We can use simple priority queue or something more complicated (see this amazing [talk about Apollo Guidance Computer](https://www.youtube.com/watch?v=xY45YE7ggng) and how it can save lives).

**Comment by pornel** [comment]
That would be very useful. In node I'm using queues *everywhere* to handle traffic spikes, and some requests are more latency-sensitive than others, so at minimum I'd like ability to add to front or back of the queue.

I do also have a use-case for super-complicated queueing, which throttles amount of requests per user, per IP address, per type of request and phase of the moon. To avoid burdening the library, maybe this could be generalized to a callback that chooses which pending task should be done next?

**Comment by floatdrop** [comment]
> I do also have a use-case for super-complicated queueing, which throttles amount of requests per user

Can you share more details about this use case? At first glance this could be achieved by creating multiple queues per user/IP address.

**Comment by pornel** [comment]
My use case is a crawler that fetches things from 3rd party sites on user request (I act as a proxy):

- there's a global limit to number of requests I'm able to process concurrently before running out of memory,
- there's a per-account limit to prevent a single account from monopolizing the service,
- there's a per-requesting-IP limit to curb abuse from people registering multiple accounts,
- there's a limit per crawled hostname how many request I'll send to the server (to avoid DoSing servers),
- there's a limit per crawled server IP (to avoid DoSing servers with a wildcard DNS).

Currently I'm using LRU maps to create queues for each IP/account/hostname. That does the job, but feels bloated - I have complicated machinery that creates and destroys lots of queues that most of the time process only 1 task ever.

Separate queues also create a problem similar to priority inversion:

If one back-end server is responding very very slowly, its queue will fill up (and that's fine). However, an earlier queue that controls number other aspect (e.g. incoming requests per account) will continue accepting requests that depend on the unresponsive back-end, eventually filling up too, and grinding everything to a halt.

OTOH if everything was in a single queue, I could skip over requests that depend on a busy back-end, and continue making progress with other requests.

**Comment by vdiez** [comment]
I did a PR #3 for this request. Please let me know what you think, still playing with it.

**Comment by floatdrop** [comment]
Added [my implementation](https://github.com/sindresorhus/p-queue/pull/4) for this issue, but it still lacks dynamic concurrency for tasks – this will be hard one, I think.

**Comment by floatdrop** [comment]
> it still lacks dynamic concurrency limit for tasks groups – this will be hard one, I think.

Actually this is achievable with custom QueueClass – it just need to track, how many operation in each group is running and take not last operation from queue, but also skip operations, that hit limit.

@pornel it would be awesome to see your implementation of QueueClass 😉
