### ISSUE TITLE
TypeError: PQueue is not a constructor

### ISSUE THREAD

**Issue by TomTruyen** [sindresorhus/p-queue#103]
So I was working on something and I decided to use pqueue using the following code:

`const PQueue = require('p-queue');
const taskQueue = new PQueue({ concurrency: 1 });`

Now I get an error on the line where I call 'new PQueue' saying the following:

`TypeError: PQueue is not a constructor
    at Object.<anonymous> (F:\Bureaublad\Latest Bot With Logger And Splitted Files\src\bot.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11`

I have no idea what causes this error. Anyone has an idea? Has something changed with pqueue? 
I'm running PQueue version 6.3.0

Thanks in advance

**Comment by TomTruyen** [comment]
fixed by downgrading to last JS version (@5.0.0)

**Comment by subhasishdas159** [comment]
I'm having this error while trying to use [broadcast-channel](https://github.com/pubkey/broadcast-channel)
I'm using next js 12 with vercel.
Vercel build is failing due to this. 
Any ideas how to solve this?

**Comment by jbasko** [comment]
@subhasishdas159 How did you resolve? I am guessing this is to do with Next.js backend trying to create it?

**Comment by DennieMello** [comment]
The problem occurs during server rendering, an example of a fix is

```typescript
  const channel = useMemo(
    () =>
      new BroadcastChannel("auth", {
        type: typeof window === "undefined" ? "simulate" : "native",
      }),
    []
  );
```

**Comment by ankurparihar** [comment]
getting the same issue, in version 6.6.2
