### ISSUE TITLE
Add function should not be async

### ISSUE THREAD

**Issue by acrodrig** [sindresorhus/p-queue#108]
The queue `add` function defined [here](https://github.com/sindresorhus/p-queue/blob/master/source/index.ts#L229) should not be `async` as there are no "awaits" in its body. Defining it as `async` breaks eslint rules such as "require-await" without need.

**Comment by sindresorhus** [comment]
I have a convention of marking functions as async when they return a promise, for readability reasons and to ensure none of the synchronous code accidentally throw a synchronous error (not the case here, but has happened before).

I don't see why the ESLint thing is relevant here. You're not linting the `p-queue` code, I asume.
