### ISSUE TITLE
refactor: async is unnecessary.

### ISSUE THREAD

**Issue by brizer** [sindresorhus/p-queue#117]
https://github.com/sindresorhus/p-queue/blob/08630e196ebc6b70759fbc32928ca7868e9214a9/source/index.ts#L231

`async` is unnecessary in this sence. `async` will bring more performance loss.

**Comment by brizer** [comment]
It is same to https://github.com/sindresorhus/p-queue/blob/08630e196ebc6b70759fbc32928ca7868e9214a9/source/index.ts#L268

**Comment by sindresorhus** [comment]
I prefer to annotate promise-returning functions as `async`, for readability reasons. The performance impact is negligible in most cases and meaningless for the methods you mentioned. These cases are also something JS engines like V8 could easily optimize for.

**Comment by brizer** [comment]
Thanks.
