### ISSUE TITLE
Vague Documentation

### ISSUE THREAD

**Issue by thejamespower** [sindresorhus/p-queue#121]
Firstly, thank you for what I believe is the best promise queue library out there!

However, there are three things that need addressing in the documentation:

- What is `queue.size`, how does it differ from `queue.pending` and why is it `0` most of the time?

- How do `concurrency` and `intervalCap` affect each other? What happens if one sets both? If I want to throttle requests, by X request per Y milliseconds, am I correct in the options:
```
intervalCap: X,
interval: Y,
carryoverConcurrencyCount: true,
// concurrency not set(?)
```

- Why is `carryoverConcurrencyCount` named such? As far as I can tell, it only affects the `intervalCap`...

**Comment by sindresorhus** [comment]
1. `.size` is the number of queued items waiting to run. `.pending` is the number of running items (no longer in the queue). We should indeed make that clearer.
2. They are just different constraints. `concurrency` limits how many things run at the same time. `intervalCap` limits how many things run in total during the interval (over time). You don't need `concurrency` for your use-case.
3. It's a bad name, I agree. I'm open to ideas for a better name.

**Comment by thejamespower** [comment]
Thanks @sindresorhus  :)
