### ISSUE TITLE
REST calls not triggered to run till entire queue added.

### ISSUE THREAD

**Issue by davidkjackson54** [sindresorhus/p-queue#123]
I have concurrency set very high in order to test concurrent REST api calls where I issue 140 calls in rapid succession..
I should get a HTTP 500 back due to flooding the server but I am not. When I traced the code, it appears that the REST calls are only being made 1 at at time.

```js
const queue = new PQueue({ concurrency: 1000 });
 (async () => {
    for (const copyFile of JSONObj.result) {
      log.debug(`1. Initial ${copyFile.includedComponent}`);
      let browseOption ="B";
      log.debug(`2. Before REST ${copyFile.includedComponent}`);
      (async () => {
        data = await queue.add(() =>
          ComponentBrowse.get({
            //componentBrowse({
            session: { session: session },
            parms: {
              component: copyFile.includedComponent,
              componentType: copyFile.includedComponentType,
              package: packageName,
              browseFromOption: browseOption,
            },
          })
        );
        log.debug(`4.Before Write  ${copyFile.includedComponent}`);
        filePath = directoryPath + "\\" + copyFile.includedComponent + dirObj.copySuffix;
        fs.writeFileSync(filePath, data);
        log.debug(`5. After Write  ${copyFile.includedComponent} with filepath ${filePath}`);
        log.debug(`Queue size: ${queue.size}`);
      })();
    }
  })();

```}

**Comment by sindresorhus** [comment]
You are using synchronous calls in the async IIFE: `fs.writeFileSync(filePath, data);`

We already have a concurrency test: https://github.com/sindresorhus/p-queue/blob/55d74e14c5ea6b77a26410089ea548a10d727bf9/test/test.ts#L55-L69

Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and I'll take a closer look.

**Comment by davidkjackson54** [comment]
I spent some time debugging this and cleaned up the code. and added more debugging.
I do a queue add in a loop containing 140 reST api calls. On each call a text file is returned wich I then wish to write to a file locally.
I am finding that all the REST calls are being queued but the first REST call is not being resolved until after all 140 calls have been queued.
I have tried with a concurrency value of 1 and 300 but it doesn;t seem to ame any difference.

 The code is now much simplified:

`  const queue = new PQueue({ concurrency: 1 });

  JSONObj.result.map(async (copyFile) => {
    const component: string = copyFile.includedComponent;
    const componentType: string = copyFile.includedComponentType;
    const location: string = copyFile.whereFrom;

    let browseOption: string;
    switch (location) {
      case "B":
        browseOption = "2";
        break;
      case "S":
        browseOption = "1";
        break;
      default:
        vscode.window.showInformationMessage(`Copy file ${component} not in Baseline or Package`);
    }
    // calls the /component/browse api
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    log.debug(`1. Queue add ${component}`);

    (async () => {
      data = await queue.add(async () =>
        //ComponentBrowse.get({
        componentBrowse({
          session: { session: session },
          parms: {
            component: component,
            componentType: componentType,
            package: packageName,
            browseFromOption: browseOption,
          },
        })
      ); // end queue add

      // promise is resolved
      log.debug(`2. Resolved ${component}`);
      const filePath: string = directoryPath + "\\" + component + dirObj.copySuffix;
      fs.writeFile(filePath, data, (err) => {
        if (err) {
          vscode.window.showInformationMessage(err.message);
          return;
        } else {
          log.debug(`3. Saving local Copybook ${component}`);
        }
      });
      log.debug(`4. Queue size: ${queue.size} Queue pending: ${queue.pending}`);
    })(); // end async
  }); // end map

  await queue.onIdle();
  log.debug(`5. All done`);
  log.debug(`Downloaded all copybooks for ${packageName} ${component} ${componentType}`);
  vscode.window.showInformationMessage(`${JSONObj.result.length} copy files havce been retrieved`);`

**Comment by davidkjackson54** [comment]
Any update on this?

**Comment by sindresorhus** [comment]
As commented above:

> Submit a pull request with a failing test and I'll take a closer look.

I'm asking this as most issues like this as just mistakes in the user's code and not an issue with the package.

**Comment by davidkjackson54** [comment]
I cannot give you a recreation as it is making REST api calls. Hence why I provided  the simple code to see if there is an issue.  It may well be a user error (mine) but if so some indication as to what might be the cause would be useful as I am mostly using the same coding style of your examples. If you think  that many issues like this are user errors then maybe the supporting doc might be a contributing factor. 
Thanks anyway. I will look at an alternative solution.
