### ISSUE TITLE
Feature request: onSize promise

### ISSUE THREAD

**Issue by Azmisov** [sindresorhus/p-queue#128]
How about having another `onSize(limit)` promise, which resolves when size <= limit? You already have `onEmpty` and `onIdle`. Personally I don't want to queue 100k+ promises right at the start. So would be nice to be able to queue them on demand when queue size drops below say 2x `concurrency`.

Could perhaps consider `onSizeBy(limit, options)` as well.

**Comment by dobesv** [comment]
This has been added in the latest release.

**Comment by Richienb** [comment]
For `size < limit`, use [`.onSizeLessThan`](https://github.com/sindresorhus/p-queue#onsizelessthanlimit):

```js
await queue.onSizeLessThan(limit)
```

For `size <= limit`:

```js
await queue.onSizeLessThan(limit + 1)
```
