### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by mysuf** [sindresorhus/p-queue#142]
version: 7.1.0

Error: Module not found: Can't resolve 'p-queue'

It works with previous major version (v6.6.1). I tried upgrading node from v12.22.1 to v14.6.1, because package.json's `exports` key was experimental in v12, however it didn't help. Replacing `exports` by `main` in package.json fixes the issue. Command: `react-scripts start`. Any idea? Thanks

**Comment by sindresorhus** [comment]
Please read the release notes. This is a problem with `react-scripts`.

**Comment by vorousjames** [comment]
linking to the release notes would be helpful since i cant find it in the readme.

**Comment by dutzi** [comment]
@sindresorhus, there is no reference to `react-script` or `module not found` in the repo, can you please elaborate?

**Comment by WilliamAlexander** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by mysuf** [comment]
@WilliamAlexander this makes sense for node.js environment (server side), but not for package imported in browser
