### ISSUE TITLE
Using p-queue with `require`

### ISSUE THREAD

**Issue by fergiemcdowall** [sindresorhus/p-queue#143]
My node project doesn't let me `import` modules. Is it possible to use p-queue with `require`? If so, what is the recommended incantation?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by fergiemcdowall** [comment]
👍

**Comment by fergiemcdowall** [comment]
If anybody stumbles upon this later, the incantation for those forced to use `require` is ->

```javascript
const queue = new (await import('p-queue')).default({concurrency: 1})
```

**Comment by otanim** [comment]
Thanks for the answer @fergiemcdowall, much appreciated!

Just in case if anyone wants to re-use the `PQueue` constructor instead of reusing the same long line of importation:
```javascript
let PQueue;
(async () => {
    PQueue = (await import('p-queue')).default;
})();

//... * anything *

const queue1 = new PQueue({concurrency: 5});

const queue2 = new PQueue({concurrency: 10});
```

**Comment by fergiemcdowall** [comment]
@otanim yes, if you account for the possible race condition when you first assign `PQueue`, then thats a nice way to do it 👍

**Comment by 8427003** [comment]
why so tick do this, some  babel ts project can't use this package
