### ISSUE TITLE
Maintenance of last Non-ESM release

### ISSUE THREAD

**Issue by konradjurk** [sindresorhus/p-queue#164]
Hi 👋

Due to our server (Nest.js, [source](https://discord.com/channels/520622812742811698/975798881667391518/975799372631662632)) as well as testing framework (Jest, [source](https://jestjs.io/docs/ecmascript-modules)) currently being incompatible or not sufficiently stable with ESM, we can't upgrade to your latest major version.

We are wondering if you are planning to continue to supply security updates to the last non-ESM release.

Thank you!

**Comment by sindresorhus** [comment]
We will backport security fixes to v6 for the foreseeable future.
