### ISSUE TITLE
Module not found: Can't resolve 'p-queue' in xxx at `7.3.0`

### ISSUE THREAD

**Issue by tkforce** [sindresorhus/p-queue#165]
I'm currently using the latest version `7.3.0`, however when I import with
```javascript
import PQueue from 'p-queue'
```
I'll get the following error:

![image](https://user-images.githubusercontent.com/7017984/182359455-c91190d5-44f8-4ed4-93cf-acabe1923b7c.png)

But when I imported with additional `/dist`
```javascript
import PQueue from 'p-queue/dist'
```

It will works as expected! (might have sth to do with the default export?)

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by olivergeorge** [comment]
Just a heads up that this was a problem for us.  We had compatibilities problems with StorybookJS and ShadowCLJS.

Things started working again once we added "main" to the package.json pointing at the same dist index file.  That fixed both.

```js
	"main": "./dist/index.js",
```

An alternative with ShadowCLJS was to configure around the problem: https://shadow-cljs.github.io/docs/UsersGuide.html#js-entry-keys

I'm not good enough friends with storybookjs to work out what configuration might help.

Perhaps there's good reasons not to add "main" to the package.json.  If it's a matter of taste, perhaps it would be a kindness would be expanding compatibility by adding "main" back in.

Thanks for your hard work.

**Comment by akinnee** [comment]
eslint was complaining:
```
error  Unable to resolve path to module 'p-queue'  import/no-unresolved
```

which went away when switching from:
```
import PQueue from 'p-queue';
```
to:
```
import PQueue from 'p-queue/dist';
```

I think it's because the package.json for this package is missing a `main` property.
