### ISSUE TITLE
Version 7.3.1 appears to be broken

### ISSUE THREAD

**Issue by NSGolova** [sindresorhus/p-queue#174]
Error message:
```
Error: Could not load /opt/build/repo/node_modules/p-queue/dist/index.js (imported by src/utils/queue.js): ENOENT: no such file or directory, open '/opt/build/repo/node_modules/p-queue/dist/index.js'
```

Usage code: https://github.com/BeatLeader/beatleader-website/blob/d4d824c339a29f8fa7eab37d2d66440db673208c/src/utils/queue.js#L1
Failed deploy run: https://app.netlify.com/sites/nostalgic-kare-ad710f/deploys/63df31ac6248ae22b190fd34

Temporary fixed by using exactly `7.3.0`

**Comment by sindresorhus** [comment]
// @Richienb

**Comment by Richienb** [comment]
The TypeScript compiler didn't automatically run on publish so the JavaScript never got built
