### ISSUE TITLE
latest update causes all instances of `add` to return response | void

### ISSUE THREAD

**Issue by vidarc** [sindresorhus/p-queue#175]
```typescript
import PQueue from 'p-queue'

const queue = new PQueue();

// has type Promise<string | void>
const result = queue.add(() => 'testing');
```
I would initially expect result to have type of `Promise<string>`. This commit https://github.com/sindresorhus/p-queue/commit/81846550274256011a2d55b06aeb36b23877eb43 seems to have changed that behavior. 

If I'm reading the types correctly, doing
```typescript
queue.add(() => 'testing', { throwOnTimeout: true })
```
should bring back the old typing, but it doesn't.

**Comment by sindresorhus** [comment]
// @Richienb

**Comment by Richienb** [comment]
Added type tests

**Comment by BeeeQueue** [comment]
This is still occurring on 7.3.4. See https://github.com/BeeeQueue/dota-matches-api/actions/runs/4212473470/jobs/7311519688

**Comment by Richienb** [comment]
> This is still occurring on 7.3.4. See [BeeeQueue/dota-matches-api/actions/runs/4212473470/jobs/7311519688](https://github.com/BeeeQueue/dota-matches-api/actions/runs/4212473470/jobs/7311519688)

The `p-queue` API could be improved. For now, pass `throwOnTimeout: true` as an option.

**Comment by tylerhellner** [comment]
Still happening on the current release.
