### ISSUE TITLE
Doc request: Why is "concurrency" not working as expected?

### ISSUE THREAD

**Issue by bf** [sindresorhus/p-queue#178]
Hey everyone, thanks for this great library.

The last hours I have debugged an issue where I set `concurrency` for `p-queue` to 40 but only had 5 processes running at a time. Now I noticed that the node-postgres database connection also has a `max_connections` setting which was at `5`.

Maybe we could add a section to the FAQ to point out that even though p-queue concurrency is set high, other things like database driver max connections can influence how many jobs run at a time.

Thanks!

**Comment by jbialobr** [comment]
It would be good if you could provide some repro that would allow to validate the above statement (if the library is used properly).

**Comment by bf** [comment]
We can close this issue. I just wanted to point out that `node-postgres` / `pg` can limit p-queue to `5` concurrent tasks unless `max_connections` for `node-postgres` is set to at least as large as the p-queue `concurrency` option.
