### ISSUE TITLE
Non-transpiled NPM module

### ISSUE THREAD

**Issue by nixolas1** [sindresorhus/p-queue#18]
Hi, we encountered a new problem a little while ago, when our npm builds started failing with the following error: 
`ERROR in vendor.bundle.js from UglifyJs
Unexpected token: name (first) [vendor.bundle.js:26373,5]`

Which we tracked to p-queue using es6 syntax in the distributed npm module. The current UglifyJS dosn't support ES6, and crashes, unless we specifically include p-queue to be babel-transpiled.

A fix would be to distribute a transpiled "ES5 modules" version on NPM, which uses ES5 syntax, but has import statements intact.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
