### ISSUE TITLE
can not run on react-native project

### ISSUE THREAD

**Issue by lovetingyuan** [sindresorhus/p-queue#180]
this lib can not be used in react native project,

` ERROR  TypeError: undefined is not a function, js engine: hermes`

**Comment by lovetingyuan** [comment]
transform of the private class field has something wrong
```js
	#onInterval(): void {
		if (this.#intervalCount === 0 && this.#pending === 0 && this.#intervalId) {
			clearInterval(this.#intervalId);
			this.#intervalId = undefined;
		}

		this.#intervalCount = this.#carryoverConcurrencyCount ? this.#pending : 0;
		this.#processQueue();
	}

```
this.#processQueue(); is not a function, hermes engine can not handle the transplied code

**Comment by sindresorhus** [comment]
You need to open an issue on Hermes instead. This package uses normal JS syntax.
