### ISSUE TITLE
 '/node_modules/eventemitter3/index.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by MarcelFinkbeiner** [sindresorhus/p-queue#184]
Hello,

I get the following error in one of my projects:
the requested module '/node_modules/eventemitter3/index.js' does not provide an export named 'default' (at index.js:13:8)

Package version: 
```json
"p-queue": "^7.3.4",
"typescript": "^5.0.2",
```

TS Config:
```json
{
  "compilerOptions": {
    "module": "ES6",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "allowJs": true,
    "target": "ES6",
    "useDefineForClassFields": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "jsx": "preserve",
    "isolatedModules": true,
    "esModuleInterop": true,
    "lib": ["ES6", "DOM"],
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

Please let me know if you need additional inforamtion!

Best regards
Marcel

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by MarcelFinkbeiner** [comment]
@sindresorhus Thank you for that information.
But how is that supposed to help me? The error is triggered within the p-queue module!
