### ISSUE TITLE
`PQueue.on` does not exist

### ISSUE THREAD

**Issue by AzureFlow** [sindresorhus/p-queue#192]
It appears like `on` isn't working, at least on `^7.3.4`. I saw #153 but it doesn't appear like there a resolution to the problem.

Given the following example:
```js
import PQueue from "p-queue";

const queue = new PQueue({concurrency: 1});
queue.on("add", () => {
    console.log(`Task is added.  Size: ${queue.size}  Pending: ${queue.pending}`);
});

let count = 0;
(async () => {
    await queue.add(() => {
        console.log("Start #1");

        return new Promise((resolve) => setTimeout(resolve, 5 * 1000));
    });

    console.log("Done #1");
})();
```

It results in:
```
TS2339: Property 'on' does not exist on type 'PQueue '.
```

Thanks.

**Comment by darinw** [comment]
It exists, however it appears to be missing from the type def.

https://github.com/sindresorhus/p-queue/blob/c12ec2e10c99698862b6d03ce28bc54e4bb02fdc/source/index.ts#L386

**Comment by himansusekhar11004** [comment]
I am also facing the same issue on v7 (queue.on doesnot exists);

**Comment by AzureFlow** [comment]
Apparently this is caused by not having the script included in your `tsconfig.json`'s `include` array.

**Comment by himansusekhar11004** [comment]
Still facing the same issue, I have includes in my tsconfig.json.

**Comment by darinw** [comment]
> Apparently this is caused by not having the script included in your `tsconfig.json`'s `include` array.

It worked for me, just make sure you are using the d.ts file
`"include": ["node_modules/p-queue/dist/index.d.ts"]`

**Comment by darinw** [comment]
> Still facing the same issue, I have includes in my tsconfig.json.

It worked for me, just make sure you are using the d.ts file
`"include": ["node_modules/p-queue/dist/index.d.ts"]`

**Comment by yovanoc** [comment]
Yes but we don't have to do this, this is the package.json of this project that have to do this
