### ISSUE TITLE
Weakmap.get is not a function

### ISSUE THREAD

**Issue by zhengyimeng** [sindresorhus/p-queue#197]
你好！
用你的库的时候遇到了一些问题，当然，我并不确认这是不是你的问题，但是我从代码的堆栈中找到了你的库里。
我没有去深入看你的库的源码，希望你可以提供一些帮助给我，万分感谢！
<img width="861" alt="image" src="https://github.com/sindresorhus/p-queue/assets/20783425/e52f45e4-4e10-4d9b-bc00-cf93b538870b">
<img width="625" alt="image" src="https://github.com/sindresorhus/p-queue/assets/20783425/df585a99-9549-4c13-b187-4e62c0215aa6">
具体问题看上去是代码的某个地方调用了，WeakSet.get 方法导致爆了很多 WeakSet.get is not a function 的错误。
这可能不是你库本身的问题，或许是依赖的某个库的问题，但是我没有太多的时候去研究它，如果你能给我提供一些帮助，或者告诉我不是你们的问题的话，那就太好了！

**Comment by liesauer** [comment]
WeakSet是内置对象，你可以在这里看下是不是浏览器版本问题导致的不支持

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by YaminZheng** [comment]
> WeakSet是内置对象，你可以在这里看下是不是浏览器版本问题导致的不支持
> 
> https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7

我知道是内部对象，但是这个对象没有 get 方法

**Comment by annie-zyp** [comment]
> 你好！ 用你的库的时候遇到了一些问题，当然，我并不确认这是不是你的问题，但是我从代码的堆栈中找到了你的库里。 我没有去深入看你的库的源码，希望你可以提供一些帮助给我，万分感谢！ <img alt="image" width="861" src="https://user-images.githubusercontent.com/20783425/266994675-e52f45e4-4e10-4d9b-bc00-cf93b538870b.png"> <img alt="image" width="625" src="https://user-images.githubusercontent.com/20783425/266994700-df585a99-9549-4c13-b187-4e62c0215aa6.png"> 具体问题看上去是代码的某个地方调用了，WeakSet.get 方法导致爆了很多 WeakSet.get is not a function 的错误。 这可能不是你库本身的问题，或许是依赖的某个库的问题，但是我没有太多的时候去研究它，如果你能给我提供一些帮助，或者告诉我不是你们的问题的话，那就太好了！

我也遇到了同样的问题

**Comment by annie-zyp** [comment]
> 你好！ 用你的库的时候遇到了一些问题，当然，我并不确认这是不是你的问题，但是我从代码的堆栈中找到了你的库里。 我没有去深入看你的库的源码，希望你可以提供一些帮助给我，万分感谢！ <img alt="image" width="861" src="https://user-images.githubusercontent.com/20783425/266994675-e52f45e4-4e10-4d9b-bc00-cf93b538870b.png"> <img alt="image" width="625" src="https://user-images.githubusercontent.com/20783425/266994700-df585a99-9549-4c13-b187-4e62c0215aa6.png"> 具体问题看上去是代码的某个地方调用了，WeakSet.get 方法导致爆了很多 WeakSet.get is not a function 的错误。 这可能不是你库本身的问题，或许是依赖的某个库的问题，但是我没有太多的时候去研究它，如果你能给我提供一些帮助，或者告诉我不是你们的问题的话，那就太好了！

请问你的问题解决了吗？

**Comment by YaminZheng** [comment]
> > 你好！ 用你的库的时候遇到了一些问题，当然，我并不确认这是不是你的问题，但是我从代码的堆栈中找到了你的库里。 我没有去深入看你的库的源码，希望你可以提供一些帮助给我，万分感谢！ <img alt="image" width="861" src="https://user-images.githubusercontent.com/20783425/266994675-e52f45e4-4e10-4d9b-bc00-cf93b538870b.png"> <img alt="image" width="625" src="https://user-images.githubusercontent.com/20783425/266994700-df585a99-9549-4c13-b187-4e62c0215aa6.png"> 具体问题看上去是代码的某个地方调用了，WeakSet.get 方法导致爆了很多 WeakSet.get is not a function 的错误。 这可能不是你库本身的问题，或许是依赖的某个库的问题，但是我没有太多的时候去研究它，如果你能给我提供一些帮助，或者告诉我不是你们的问题的话，那就太好了！
> 
> 请问你的问题解决了吗？

我换了另一个库实现

**Comment by annie-zyp** [comment]
您的邮件我已收到，谢谢！

**Comment by YaminZheng** [comment]
> 您的邮件我已收到，谢谢！

你可以试试 npm i tslib

**Comment by annie-zyp** [comment]
> > > 你好！ 用你的库的时候遇到了一些问题，当然，我并不确认这是不是你的问题，但是我从代码的堆栈中找到了你的库里。 我没有去深入看你的库的源码，希望你可以提供一些帮助给我，万分感谢！ <img alt="image" width="861" src="https://user-images.githubusercontent.com/20783425/266994675-e52f45e4-4e10-4d9b-bc00-cf93b538870b.png"> <img alt="image" width="625" src="https://user-images.githubusercontent.com/20783425/266994700-df585a99-9549-4c13-b187-4e62c0215aa6.png"> 具体问题看上去是代码的某个地方调用了，WeakSet.get 方法导致爆了很多 WeakSet.get is not a function 的错误。 这可能不是你库本身的问题，或许是依赖的某个库的问题，但是我没有太多的时候去研究它，如果你能给我提供一些帮助，或者告诉我不是你们的问题的话，那就太好了！
> > 
> > 
> > 请问你的问题解决了吗？
> 
> 我换了另一个库实现

你换的什么库啊？试了npm i tslib 也不行
