### ISSUE TITLE
Is there any p-* util collection?

### ISSUE THREAD

**Issue by fritx** [sindresorhus/p-queue#2]
Including p-throttle, p-debounce, p-limit, etc..

**Comment by sindresorhus** [comment]
You mean gathered into one module?

**Comment by fritx** [comment]
Yeah... like p-lodash somehow.

**Comment by sindresorhus** [comment]
Yes, it's planned, but I'm not there yet. Will let you know when I have something. You could watch https://github.com/sindresorhus/promise-fun for updates.

**Comment by fritx** [comment]
Awesome.. would you open the issues section of promise-fun?
I have some idea to share too!

**Comment by sindresorhus** [comment]
@fritx Gitter-only for now. I don't have time to deal with an issue tracker there yet (usually a lot of overhead). Can we chat here https://gitter.im/promisefun/Lobby ?
