### ISSUE TITLE
Add execution control

### ISSUE THREAD

**Issue by onury** [sindresorhus/p-queue#21]
Currently the queue is auto-executed in `p-queue`.
Is it possible to add ability to start executing the queue at a later time?

### Example Case
- Some app events are fired (globally) and handled within each controller (of views).
- When received, there are API calls to be made and some UI lists to be filled in. 
- But operations need to be queued and executed when the UI/view is ready.

### Suggestion: an `autorun` option and `.run()` method...
```js
const queue = new PQueue({ concurrency: 1, autorun: false });

app.on('locationChanged', event => {
    queue.add(() => got(endpoint)).then(result => {
        // do UI stuff
    });
});

view.on('ready', () => queue.run());
```
What do you think?

**Comment by sindresorhus** [comment]
Makes sense to me. I would name it `autoStart`, and add `.start()` and `.pause()` methods.

@floatdrop What do you think?

**Comment by onury** [comment]
`.start()` suggests a `.stop()` method which does not fit. That's why I suggested `.run()`.

`pause()` would not be an actual "pause", cannot be immediate. Queue will be put on hold after the current execution completes. So maybe `.hold()` would be better... just my $0.02

**Comment by sindresorhus** [comment]
I would say that depends on what you consider `.pause()` to mean. For me, it means pausing the queue itself, not the tasks. I guess either way it could be clarified in the docs. I just think it would be useful to have a way to pause the queue. Maybe you want to stop executing tasks when the user goes offline, but still want to queue them up for when the user becomes online again.

**Comment by onury** [comment]
No, I actually agree, pause/hold ability should also be added. Just didn't want to complicate it in the initial post. 

Anyway, my concern was just the API naming, semantics.. Can be clarified in docs, as you said..
