### ISSUE TITLE
If a queue is cleared before completion, newly-added items don't run.

### ISSUE THREAD

**Issue by greeze** [sindresorhus/p-queue#23]
`queue.clear()` doesn't reset `_pendingCount` to 0, preventing newly-added items from running.

**Comment by sindresorhus** [comment]
Setting `_pendingCount` to `0` would be incorrect as they're still pending even though the queue is cleared.

**Comment by greeze** [comment]
Hmmm... I may misunderstand the intent of `clear()`. I took it to mean that the remaining items in the queue would be either canceled or ignored, essentially left to fend for themselves, leaving me with a shiny new empty queue to add items to. What _seems_ to happen, though, is that clearing the queue causes the current item not to report its completion, and the next queue item never gets run. Am I misunderstanding?

Maybe a better question would be: Is there a way I can cancel a queue midway through its execution, clear the remaining items, and then add a batch of new items and start over from the top?

**Comment by sindresorhus** [comment]
Calling `.clear()` clears out the queue of unstarted queue items. Promises are not cancelable, so we can't do anything about the ones that have already begun.

When you set `_pendingCount = 0`, you're basically just forgetting about the pending items and pretending that they don't exist anymore. That might be fine for your use-case, but it could lead to memory issues if you have too many pending items.

I think we should document the current behavior better. And I'm open to ideas on how to improve this, but we're limited by promise limitations.

**Comment by szmarczak** [comment]
> Promises are not cancelable, so we can't do anything about the ones that have already begun.

We could support `p-cancelable`.

**Comment by ltetzlaff** [comment]
> We could support `p-cancelable`.

Cool idea,
alternatively what about something like changing `clear` to a:

```ts
async flush() {
  await Promise.all(this.queue)
}
```

**Comment by szmarczak** [comment]
@ltetzlaff Nah. It's the same as `await this.onIdle()`. Clear is meant to really **clear** items in the queue.
