### ISSUE TITLE
Combination with p-retry

### ISSUE THREAD

**Issue by entrptaher** [sindresorhus/p-queue#25]
Consider the following function, it will throw once run.

```js
function errorFn (){
  throw new Error('Should Throw');
};
```
We can add this to the queue by the following code.

```js
queue.add(errorFn)
```
How do we impliment a function to re-queue it in case it throws an error? Can we use p-retry and p-queue together to achieve that? Can this be added as a function to p-queue?

Here is a sample implementation, 
https://github.com/entrptaher/p-requeue/blob/master/test.js

**Comment by szmarczak** [comment]
> How do we impliment a function to re-queue it in case it throws an error?

```js
queue.add(fn).catch(e => queue.add(secondFn))
```

**Comment by entrptaher** [comment]
@szmarczak that's not re-queue the same function ;)

**Comment by szmarczak** [comment]
> that's not re-queue the same function ;)

Can you elaborate?

> Can we use p-retry and p-queue together to achieve that?

To achieve what? Please specify :) If you want to use `p-retry`, feel free.

```js
queue.add(pRetry(fn))
```

**Comment by entrptaher** [comment]
I'll test it out and see how it differs. Really thanks for such solution. I made a whole new function for this instead from p-queue. :D
