### ISSUE TITLE
Exceptions swallowed

### ISSUE THREAD

**Issue by rantecki** [sindresorhus/p-queue#26]
Any exceptions raised in the promise appear to be swallowed, invoking the notorious 'Unhandled promise rejection' message under Node.js.

Is there any way to catch/handle errors that occur while processing a queue?

Perhaps a `q.onError(callback)` kind of thing?

Of course one could just add a global handler for unhandled rejections via `process.on('unhandledRejection'...`, although you then lose the ability to trap/handle errors within a particular context.

**Comment by lirbank** [comment]
To catch the error, you can do this:
```js
q.add(() => someJob()).catch((error) => {
  console.log(error);
})
```

Or using async/await:
```js
(async () => {
  try {
    await q.add(() => someJob());
  } catch(error) {
    console.log(error)
  }
})();
```

Full example:
```js
import Queue from 'p-queue';

async function someJob(i) {
  const delay = Math.round(Math.random() * 1000);
  console.log('start', i.toString().padStart(2), delay);
  await new Promise(r => setTimeout(r, delay));
  console.log('end  ', i.toString().padStart(2));
  if (i === 2) throw new Error('some error ' + i);
  return 'some result';
}

const q = new Queue({concurrency: 3});

let c = 0;
q.add(() => someJob(c++)).catch(error => {
  console.log(error);
});
q.add(() => someJob(c++)).catch(error => {
  console.log(error);
});
q.add(() => someJob(c++)).catch(error => {
  console.log(error);
});
q.add(() => someJob(c++)).catch(error => {
  console.log(error);
});

let c = 0;
(async () => {
  try {
    await q.add(() => someJob(c++));
    await q.add(() => someJob(c++));
    await q.add(() => someJob(c++));
    await q.add(() => someJob(c++));
  } catch (e) {
    console.log(e);
  }
})();
```

StackBlitz fiddle here: https://stackblitz.com/edit/react-ps6xjs (open your browser console to see the results).

**Comment by rantecki** [comment]
Thanks for this.  I appreciate the fiddle.

In the async/await example it appears that you're waiting for each job to finish before you even add the next job to the queue.  That kind of defeats the purpose of the queue doesn't it?

I guess I was hoping for something more like this:

``` js
  q.add(() => someJob(c++));
  q.add(() => someJob(c++));
  q.add(() => someJob(c++));
  q.add(() => someJob(c++));
  try {
    await q.onIdle();
  } catch (e) {
    console.log(e);
  }
```

Or even this:

``` js
  try {
    q.add(() => someJob(c++));
    q.add(() => someJob(c++));
    q.add(() => someJob(c++));
    q.add(() => someJob(c++));
    await q.onIdle();
  } catch (e) {
    console.log(e);
  }
```

Unfortunately the error is uncaught in these cases.

This does however seem to work:

``` js
  const jobs = [];
  jobs.push(q.add(() => someJob(c++)));
  jobs.push(q.add(() => someJob(c++)));
  jobs.push(q.add(() => someJob(c++)));
  jobs.push(q.add(() => someJob(c++)));
  try {
    await Promise.all(jobs);
  } catch (e) {
    console.log(error);
  }
  await q.onIdle();
```

Note that in this case the `Promise.all()` is really doing the job of `q.onIdle()`, making the `q.onIdle()` call fairly redundant (apart from waiting for the remaining non-errored jobs to finish).  In my view this seems like a doubling-up and `q.onIdle()` should really be able to do this by itself without the extra boilerplate.

Thoughts?

**Comment by lirbank** [comment]
That's right, Promise.all is your friend when handling (errors of) parallel promises. It has nothing to do with p-queue, it's just how Promises in general may be handled. I was just trying to give a (too) simple example of error handling with promises, great that you figured it out 😃  

I guess the use case for p-queue is something like this; Imagine you have 100,000 items you need to write to the DB (can be a REST call or anything else that takes resources or takes time). Then you can take the following two avenues in vanilla JavaScript:
```
for (const item of items) {
  await writeToDB(item);
}
```
Which would write them one a the time: Ugh, this will be slow, so let's parallelize:
```
await Promise.all(items.map(item => writeToDB(item)));
```
Ok, this should be much faster. But jikes, all of the writes will go of at once. Do we really want to fire 100,000 (or say the length of `items` is arbitrary so we don't even know ahead of time) write requests at once, can our DB handle it, etc?

Ok, so we want number two, but we want to limit the number of parallel writes at the same time. Enter p-queue!
```
await Promise.all(items.map(item => q.add(() => writeToDB(item))))
```
Now p-queue will prevent more than X promises from being "in progress" at any given time.

**Comment by rantecki** [comment]
What you say makes sense.  I probably don't need to use onIdle() at all.  Thanks for the help.

**Comment by catamphetamine** [comment]
Doing `try { await Promise.all(tasks) }` manually is bad code and defeats the whole point of using the queue.
As @rantecki said, it would be much more logical to have:

```js
  q.add(() => someJob(c++));
  q.add(() => someJob(c++));
  q.add(() => someJob(c++));
  q.add(() => someJob(c++));
  try {
    await q.onIdle();
  } catch (e) {
    console.log(e);
  }
```
