### ISSUE TITLE
Sync function error breaks everything

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/p-queue#32]
What if [`fn()`](https://github.com/sindresorhus/p-queue/blob/master/index.js#L96) fails? Example:

```javascript
(async function() {
	let queue = new PQueue({ concurrency: 1 });
	
	queue.add(() => { throw 'x' }).catch(console.log);
	queue.add(() => { throw 'y' }).catch(console.log);
})();
```

**Comment by floatdrop** [comment]
@szmarczak I'm not sure, but seems like line should be `Promise.resolve(fn)`.

**Comment by szmarczak** [comment]
@floatdrop According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve) (`Promise.resolve(value)`):

> [value] Argument to be resolved by this Promise. Can also be a Promise or a thenable to resolve.

So in this case
```javascript
await Promise.resolve(function a() { return 123; })
```

it doesn't return `123`. Instead it gives `ƒ a() { return 123; }` because the function isn't thenable nor a promise - it's just a function.

Here's what I came up with:
```javascript
			const run = () => {
				this._pendingCount++;

				Promise.resolve((async _ => fn())()).then( // previously it was Promise.resolve(fn())
					val => {
						resolve(val);
						this._next();
					},
					err => {
						reject(err);
						this._next();
					}
				);
			};
```
Maybe there's a better way to solve this problem?

**Comment by szmarczak** [comment]
@floatdrop IMO the workaround I did would work, but it is incompatible with node `<7.10.1`. I don't know if it's a good idea to use `try/catch`. Then it would look like that:

```javascript
			const run = () => {
				this._pendingCount++;
				try {
					Promise.resolve(fn()).then(
						val => {
							resolve(val);
							this._next();
						},
						err => {
							reject(err);
							this._next();
						}
					);
				} catch (err) {
					reject(err);
					this._next();
				}
			};
```

**Comment by szmarczak** [comment]
@sindresorhus what do you think about this?
