### ISSUE TITLE
Add option to update concurrency

### ISSUE THREAD

**Issue by dcolens** [sindresorhus/p-queue#38]
I have a use case where I need to update concurrency based on queue execution results, what I'd like to do is on a specific output, decrease concurrency (I understand it would not be instant but would have to wait until items are dequeued), maybe the call to decrease concurrency could return a Promise that resolves once the new concurrency is reached ?

**Comment by szmarczak** [comment]
Currently that's not possible, but I'll send a PR.

**Comment by sindresorhus** [comment]
Sounds useful. PR welcome.

**Comment by zkochan** [comment]
I think I need this as well to implement https://github.com/pnpm/pnpm/issues/1572
