### ISSUE TITLE
Compile to ES5?

### ISSUE THREAD

**Issue by trungdq88** [sindresorhus/p-queue#39]
Can we compile `index.js` to ES5? `create-react-app` is complaining when I try to build.

![image](https://user-images.githubusercontent.com/4214509/43825315-a13926b0-9b1e-11e8-9370-58caaf04e69f.png)

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.

**Comment by trungdq88** [comment]
Thank you
