### ISSUE TITLE
Wait until the size <= concurrency

### ISSUE THREAD

**Issue by palmic** [sindresorhus/p-queue#48]
When i set concurrency to 10, i would expect `await queue.add()` will let me put 10 jobs to queue and will keep Promise pending just if the queue is full (10+)
Current implementation is always waiting for job to complete so if i am adding in iteration, it does not let iteration to fill the queue.
This expected behaviour is present for instance in `async.queue` but without promises support.

**Comment by szmarczak** [comment]
You can make a wrapper for that:

```js
const add = fn => new Promise(resolve => {
    const p = queue.add(async () => {
        resolve(p);
        await fn();
    });
});
```

(not tested, but it should work)

I guess we can create `queue.isFull` property...

**Comment by palmic** [comment]
Thank you for response, but i dont get the purpose of this module if this is not default behaviour.
If ill just "do the work" directly synchronously, it will make the same like with your queue in default settings. If ill set this wrapper, its about 25% of code to make "my own" Queue class with this behaviour.

You should at least put this use case into your readme, because this will be most common use case which will be looking for people migrating from callbacks to Promises.

Thank you again and have a nice day. (You can close this if you want)

**Comment by szmarczak** [comment]
> i dont get the purpose of this module if this is not default behaviour

Have you read the docs? No, so don't judge it. You're not looking for this.

> If ill just "do the work" directly synchronously, it will make the same like with your queue in default settings

Indeed, so we've created settings so you can customize what you want. Also, we support async functions.

> If ill set this wrapper, its about 25% of code to make "my own" Queue class with this behaviour.

Then why don't you create your own queue lib?

> You should at least put this use case into your readme

You haven't specified the use case. What's that?

**Comment by palmic** [comment]
ok, sorry szmarczak, i didn't intend to be so offense, i just didn't get it.
Your point of view is relevant enough, my mistake.

My use case is to fill the queue independently on tasks processing (asynchronously) and to be waiting on next queue.add() just in case of full queue.
I solved this by writing my own queue class, so its irrelevant now.

Have a nice day and really sorry if it was rude (which could be)
have a nice day,
Michal.

**Comment by szmarczak** [comment]
> i didn't intend to be so offense, i just didn't get it.

No worries. I haven't taken it personally, as many people don't read the docs.

> I solved this by writing my own queue class, so its irrelevant now.

You could inherit from PQueue (just change the "add" function).

**Comment by Rafael09ED** [comment]
Can we close this issue?

**Comment by palmic** [comment]
i think so.
