### ISSUE TITLE
onEmpty() is not the same as queue.pending === 0

### ISSUE THREAD

**Issue by rclark** [sindresorhus/p-queue#5]
In a use-case where 
- I have 16 async things to do
- I don't want more than 8 "in-flight" concurrently
- I want to know when all 16 are done

I expected to be able to 

```js
const assert = require('assert');
const Queue = require('p-queue');
const queue = new Queue({ concurrency: 8 });
const tasks = Array(16).fill(0);

const work = () => new Promise((resolve) => {
  setTimeout(resolve, Math.random() * 2000);
});

tasks.forEach(() => {
  queue.add(() => work());
});

queue.onEmpty()
  .then(() => assert.equal(queue.pending, 0));
```

However this is not the case -- `onEmpty()` resolves as soon as there's space in the queue for the new tasks to launch, not when all the tasks that have been enqueued are resolved. Does this sound right, and if so, would you be interested in another method that provides a promise that resolves when `queue.pending` reaches `0`?

**Comment by floatdrop** [comment]
@rclark `add` returns promise, so you can do something like this to wait for all tasks:

```js
tasks.map(() => queue.add(() => work()));

Promise.all(tasks).then(console.log('All finised'));
```

**Comment by rclark** [comment]
Understood. Thanks!
