### ISSUE TITLE
CHANGELOG is missing

### ISSUE THREAD

**Issue by kachkaev** [sindresorhus/p-queue#51]
> This is the same as https://github.com/sindresorhus/execa/issues/154, I was surprised to find that both packages are by you @sindresorhus! 🙂

I was upgrading my project dependencies and noticed that p-queue bumped from 2.4.2 to 3.0.0. This looked like a certain breaking change, so I went to search for a CHANGELOG to then update my code if needed.

I could not find any info on the [releases page](https://github.com/sindresorhus/p-queue/releases) and a commonly used `CHANGELOG.md` file was also missing. It'd be great if at least one of these things was added to p-queue so that people were wasting less time trying to figure out whether they can safely bump or not. This can save hundreds of hours for folks around the world.

**Comment by onury** [comment]
@kachkaev I agree. For now [see this](https://github.com/sindresorhus/p-queue/compare/v2.4.2...v3.0.0). 
Major breaking change seems to be dropping support for Node v4.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/p-queue/releases/tag/v3.0.0
