### ISSUE TITLE
Not depend on events?

### ISSUE THREAD

**Issue by olofd** [sindresorhus/p-queue#55]
In 3.1.0 the dependency of EE => events was introduced. That means this library does no longer work on the web.

**Comment by RobTS** [comment]
Nor does it work on React Native any more

**Comment by olofd** [comment]
@sindresorhus Can we use this: https://github.com/primus/eventemitter3 or something instead?

**Comment by sindresorhus** [comment]
I think Webpack shims the `events` module (?)

**Comment by olofd** [comment]
React Native uses Metro, not Webpack. And why would we need to shim a package to make an easy module like this to be platform independent?

I thin the best solution is to have your own event-emitter included if you want to use on in the package and not always have dependencies. But that's my opinion.

**Comment by sindresorhus** [comment]
@olofd I would usually disagree, as my main target is Node.js. Bundlers enable support for browsers, etc. But I'm willing to make an exception here as this module is fairly popular for React Native and browser usage.

PR welcome to use https://github.com/primus/eventemitter3 and update to docs to reflect that fact.

**Comment by vladimiry** [comment]
> I think Webpack shims the events module (?)

- Webpack is not the only bundler.
- Webpack doesn't always ship the `events` shim to the bundle. It won't do this for example in the case of [electron-renderer](https://webpack.js.org/configuration/target) target using.

**Comment by rexxars** [comment]
Opened #58 to address this by replacing `events` with `eventemitter3`
