### ISSUE TITLE
[TypeScript] Index signature is missing in type 'DefaultAddOptions'

### ISSUE THREAD

**Issue by roblav96** [sindresorhus/p-queue#66]
Since upgrading `typescript@3.5.1` I get this compile error:
```
node_modules/p-queue/index.d.ts:81:54 - error TS2344: Type 'DefaultAddOptions' does not satisfy the constraint 'QueueAddOptions'.
  Index signature is missing in type 'DefaultAddOptions'.

81  EnqueueOptionsType extends PQueue.QueueAddOptions = PQueue.DefaultAddOptions
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~
```
My `tsconfig.json` looks like:
```json
{
	"compilerOptions": {
		"lib": ["esnext"],
		"module": "commonjs",
		"target": "es5"
	}
}
```

**Comment by callmehiphop** [comment]
I *think* the issue is that [TypeScript@3.5](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/) made a breaking change where

> `{ [k: string]: unknown }` is no longer a wildcard assignment target

Their suggestion is to use `any` instead, which appears to fix the issue for me, but I'm not sure if that's the way to go or not.
