### ISSUE TITLE
set timeout options but cann't  catch the timeoutError

### ISSUE THREAD

**Issue by emily-juan** [sindresorhus/p-queue#67]
const PQueue = require('p-queue');

const queue = new PQueue({ concurrency: 1, timeout: 5000, throwOnTimeout: true });

const delay = async (ms) => {
  await new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log('timeout');
      resolve();
    }, ms)
  });
};

try {
  queue.add(() => delay(10000))
} catch(err) {
  console.log(err);
}

This is my little demo.
I want to catch the timeoutError

**Comment by emily-juan** [comment]
npm instal p-queue is not the latest code

**Comment by sindresorhus** [comment]
There's a new release now.
