### ISSUE TITLE
Unusable in browser environment

### ISSUE THREAD

**Issue by vjancik** [sindresorhus/p-queue#7]
There is no transpiled ES5 distribution which could safely be used in the browser.

I want to use it in a web application. Do you plan to create a ES5 distributable?

I will try to transpile it with my Babel config, but that fails with larger libraries, that's why the convention is to distribute a transpiled version.

Do you see any reason why this library shouldn't be usable on the web?

Thank you for your time!

**Comment by SamVerschueren** [comment]
Because we target Node and not the browser. If you want support for ES5 you will have to transpile it yourself. I asked Sindre to answer this once and for all in his [AMA](https://github.com/sindresorhus/ama/issues/4460).

**Comment by BradDenver** [comment]
@vjancik if you are using webpack and babel then you could use something like
```
rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!p-queue)/,
        use: "babel-loader",
      },
 ],
```
to exclude all node modules except p-queue from being transpiled by babel.

**Comment by NemoAlex** [comment]
@BradDenver Thanks, that helps a lot.
@SamVerschueren The link should be https://github.com/sindresorhus/ama/issues/446

**Comment by mesqueeb** [comment]
@SamVerschueren is this still the case? I can't find anything in the readme on wether we can use this in modern browsers.
The Sindresorhus AMA also didn't clarify much.
Is there any suggestion on if/how we can use this in the browser?

**Comment by SamVerschueren** [comment]
It all depends on your setup probably.

Most frontend projects use bundlers like Vite which should handle all of it for you.

If you want to use it without any bundlers, you might be able to get it to work as browsers have good ESM support these days. Although you will have to fiddle around with import maps and what not.
