### ISSUE TITLE
v6.0.0 is broken

### ISSUE THREAD

**Issue by vkbansal** [sindresorhus/p-queue#70]
No `main` entry is defined in `package.json`. Hence bundling is failing with webpack.

https://unpkg.com/p-queue@6.0.0/

**Comment by przemyslawzalewski** [comment]
I've created PR for that issue - https://github.com/sindresorhus/p-queue/pull/69

**Comment by vkbansal** [comment]
Yeah I did not see that before creating the issue. I had also opened one #71 but closed it after seeing this.
