### ISSUE TITLE
Typescript 3.5.2 compatibility issue

### ISSUE THREAD

**Issue by legraphista** [sindresorhus/p-queue#77]
Upgrading from TS version `3.4.5` to `3.5.2` results in the following compile time error:

```
$ tsc 
node_modules/p-queue/index.d.ts:79:47 - error TS2344: Type 'DefaultAddOptions' does not satisfy the constraint 'QueueAddOptions'.
  Index signature is missing in type 'DefaultAddOptions'.

79  EnqueueOptionsType extends QueueAddOptions = DefaultAddOptions
                                                 ~~~~~~~~~~~~~~~~~


Found 1 error.
```

It looks like `QueueAddOptions` has a index definition but `DefaultAddOptions` does not, nor it extends `QueueAddOptions`.

**Comment by sindresorhus** [comment]
// @vkbansal

**Comment by legraphista** [comment]
My bad, I was on version `4.0.0` and it looks to be fixed in https://github.com/sindresorhus/p-queue/commit/c97cad801ad6049d9c8e9303289c8a7a5eff0ac4
