### ISSUE TITLE
6.x import signature

### ISSUE THREAD

**Issue by jsg2021** [sindresorhus/p-queue#79]
I just tried updating to 6, and it didn’t go as expected (from 5.0.0) :} 

I’m using [esm](https://github.com/standard-things/esm) on node. I have a `.mjs` file importing this lib and the loader is not [unwrapping the default export](https://github.com/standard-things/esm/issues/825). I think this is expected because the lib is compiled TypeScript and outputs cjs with a bundler-friendly esm flag. Does TypeScript have a compile target of esm? If so, you could add a `“module”: ‘dist/esm.js”` or something and that would make this work transparently with esm users (who opt to bite the `mjs` bullet)

This can be closed if this idea is not desirable. I’m just playing with esm as it currently stands in node to get a feel.

**Comment by sindresorhus** [comment]
> Does TypeScript have a compile target of esm?

Yes

> If so, you could add a “module”: ‘dist/esm.js” or something and that would make this work transparently with esm users (who opt to bite the mjs bullet)

Not interested in compiling to multiple targets. I don't even think that's possible with TypeScript. I plan to switch everything over to ESM when it's out in Node.js without a flag. Until then, it's CJS. It's up to you to handle that.

In this case, it's seem more like a bug in the `esm` package though.

**Comment by jdhiro** [comment]
As a workaround, this did the trick for me:

```
import pq from 'p-queue'
const PQueue = pq.default
```

However, I'm still a tad confused why this works and `import { default as PQueue } from 'p-queue'` does not.

**Comment by clibu** [comment]
+1 
``import PQueue from 'p-queue'`` works in the Browser using parcel.js to build. But it does not work in Node.js 
@jdhiro solution does work in Note, but is messy.

**Comment by smashah** [comment]
`import PQueue from 'p-queue'` works in ts-node

**Comment by ecolss** [comment]
> +1
> `import PQueue from 'p-queue'` works in the Browser using parcel.js to build. But it does not work in Node.js
> @jdhiro solution does work in Note, but is messy.

Same issue with Node, did you find a solution?
