### ISSUE TITLE
Promise when all actions in the queue are finished entirely

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/p-queue#9]
Currently it doesn't look like it's possible to wait until all promises are resolved, or am I missing something?

I tried to use `onEmpty()`. The thing is that `onEmpty()` can get called before all promises are resolved. It just triggers when `next()` is called on the queue and there are no more items to be processed.

The promise returned by `.add()` is not what I need either because when you use a concurrency of 5, the last `.add()` might resolve the as the first one.

Now that I'm typing this, I might not be using the correct library. Maybe I should have a look at `p-throttle`, although I like how `PQueue` works :).

**Comment by floatdrop** [comment]
This should work for you:

```js
await Promile.all(tasks.map(task => pQueue.add(task)));
```

Maybe this should be added in readme.

**Comment by SamVerschueren** [comment]
Oh yes, off course! Totally missed that. Would ne nice to have an example in the readme. Switched to pLimit in the mean time and works great as well.

**Comment by sindresorhus** [comment]
@floatdrop Should we maybe expose a convenience method for this? Seems like a common use-case.

**Comment by floatdrop** [comment]
@sindresorhus `addAll` sounds good to me.

**Comment by edorivai** [comment]
@floatdrop Your workaround works fine if all queue items are available up front, but if items are streamed into the queue, the workaround is less ideal. `onNonePending` is something I could use. Does this make sense?

P.S. See #12 for use case details

**Comment by floatdrop** [comment]
@edorivai I would go with this code:

```js
const queue = new PQueue({ concurrency: 20 });
const cursor = getSomeAsyncCursor();
const work = [];

let item;
while (item = await cursor.next()) {
    if (!item) { break; }
    work.push(queue.add(() => processItem(item));
}

await Promile.all(work);
cleanUpAfterMyself();
```

This will cap concurrent `processItem` runs to `20`, but will read all cursor items before hand. I think you will need something like async forEach with limit, that will await on `next`.

**Comment by edorivai** [comment]
@floatdrop Yeah, you're right. This is actually how I'm using it in production right now. But I'm also running into a problem where I have to process a really large data set, which I cannot keep in memory (~2 million items). So saving all the work into an array is not ideal, and at a certain scale not even possible.

This is actually the entire reason for me to start using `p-queue`, and having a convenience method for when `size === 0 && pending === 0` would be really nice here.

**Comment by floatdrop** [comment]
@edorivai okay, let's move this discussion to #12

**Comment by TrevorHinesley** [comment]
Does this actually work with the concurrency set? Wouldn't `addAll` only count as one concurrent action?

Let's say concurrency is set to 5, would 5 of the methods in the array passed to `addAll` execute at any one time, or just one at a time? Seems as if it's one at a time.

**Comment by TrevorHinesley** [comment]
Tested -- concurrency works as expected :)
