### ISSUE TITLE
pqueue clear no effect

### ISSUE THREAD

**Issue by ognif** [sindresorhus/p-queue#93]
If I call pqueue clear at the beginning of my function to avoid uncontrolled increase of the tasks, the p-queue seems to ignore this command. The queue is still complete full after call 

`await queue.clear();`

How to reliable delete / clear the queue?

**Comment by sindresorhus** [comment]
It would be helpful if you could submit a pull request with a [failing tests](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests). That would help getting this fixed faster if it's actually a bug. 🙏
