### ISSUE TITLE
`carryoverConcurrencyCount` docs are vague

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/p-queue#99]
Ahoy 🚢 

The [`carryoverConcurrencyCount`](https://www.npmjs.com/package/p-queue#carryoverconcurrencycount) option could use some more verbose documentation. In toying with the package, it's not entirely clear what option value produce what behavior. 

Perhaps even an `examples` directory that covered how this works?

**Comment by sindresorhus** [comment]
Can you be more specific about what's unclear about it? For now, I would recommend looking at its tests at that might clarify how it should be used.

// @Rafael09ED

**Comment by Rafael09ED** [comment]
`carryoverConcurrencyCount` is asking whether it should carryover any incomplete promises into the next interval and apply that number against the limit cap. To rephrase it it determines whether the interval cap limits how many can start or how many can finish in the given time. 
For example, if you can only have 5 connections at a time and are rate limited, you would set `carryoverConcurrencyCount` to `true` to make sure you don't go over 5 connections.
Does that help any?

**Comment by shellscape** [comment]
@Rafael09ED that's the good stuff I was looking for in the readme. Thank you for adding that. Typically for options that are boolean, I recommend (and look for) a format such like:

> If `true`, the thing behaves like one way. If `false`, thing behaves another way.

The paragraph you replied with above would be an absolute value-add to the readme!

**Comment by Rafael09ED** [comment]
How does this look?

##### carryoverConcurrencyCount

Type: `boolean`\
Default: `false`

Whether any incomplete promises should be carried over into the new interval and applied against the `intervalCap`.
If `true`, `intervalCap` limits how many can finish. If `false`, `intervalCap` limits how many can start.

Useful in preventing rate limit overages.

**Comment by shellscape** [comment]
> intervalCap effectively limits how many can finish

This threw me off, because it doesn't seem to relate (with that verbiage). We'd been talking about tasks/promises starting and this tosses finishing in the mix.

I'd tweak it a bit:

```markdown
##### carryoverConcurrencyCount

Type: `boolean`\
Default: `false`

If `true`, specifies that an incomplete `Promise` should be carried over into the next interval and counted against the `intervalCap`. If `false`, an incomplete promise will continue to run independent of the next interval and will not count towards the `intervalCap`.
```

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/p-queue/pull/100.

**Comment by shellscape** [comment]
Thanks for tackling this.
